### DISCUSSION TITLE
Unable to authenticate to API "Please provide token"

### DISCUSSION THREAD

**Discussion by sidhoah8** [codeaffen/phpipam-ansible-modules#52] [Q&A]
Thanks for creating these Ansible modules. They look really useful and I look forward to using them.  But I've tried using the basic examples to create a playbook using the codeaffen.phpipam.vlan and codeaffen.phpipam.address modules and no matter what I do, they both fail authentication.

I modified the api.py class in phpypam to print the output of the requests response as otherwise, no useful information is shown:

```        
          if result['code'] not in (200, 201) or not result['success']:
              print(result) # added otherwise no error details shown
              raise PHPyPAMException(code=result['code'], message=result['message'])
```

and now I can see the following error in the Ansible output:

`module_stdout": "{'code': 403, 'success': False, 'message': 'Please provide token', 'time': 0.001}\n"`

I don't see anywhere that I can provide the token in Ansible.  I was going to raise a bug issue and look further... but I wonder if this is user error? Am I supposed to define the "App code" somewhere or a token?  I've tried creating a fresh Python virtual environment with the latest ansible, phpypam, inflection packages but no difference.

**Comment by cmeissner** [comment]
Hi @sidhoah8,

thank you for asking question here. Can you please provide your ansible playbook so that I can try to reproduce your issue here?
Without these information I would guess that you try to connect to an unencrypted (http) api endpoint. This 

> I modified the api.py class in phpypam to print the output of the requests response as otherwise, no useful information is shown:
>
>        if result['code'] not in (200, 201) or not result['success']:
>            print(result) # added otherwise no error details shown
>            raise PHPyPAMException(code=result['code'], message=result['message'])

Good workaround for your local debugging. You also can extend `phpypam/core/exceptions.py` to handle these issue too and than open a pull request.

**Comment by sidhoah8** [comment]
Hi @cmeissner

Thanks for the quick reply.  Here's the playbook:
```
---

- name: phpIPAM testing
  hosts: localhost
  gather_facts: false

  vars:
    phpipam_server_url: "https://MY_PHPIPAM_INSTANCE"
    phpipam_login_user: "MY_OWN_AD_USERID"
    phpipam_login_password: 'MY_OWN_AD_PASS'
    phpipam_app_id: "ansible"

  tasks:
    - name: "Create vlan"
      codeaffen.phpipam.vlan:
        username: "{{ phpipam_login_user }}"
        password: "{{ phpipam_login_password }}"
        server_url: "{{ phpipam_server_url }}"
        app_id: "{{ phpipam_app_id }}"
        validate_certs: no
        name: "my vlan"
        vlan_id: 1337
        state: present
```

As you see, I'm trying to connect via HTTPS. The API settings look as follows:
![phpipam-api-settings](https://user-images.githubusercontent.com/56875903/108829730-d1e09f00-75c8-11eb-99dc-ef263bd25948.png)

And yep, good idea for the exception handling. I'm new to git but trying to learn so I will have a look at extending exceptions.py in phpypam :-)
