### ISSUE TITLE
Custom fields support

### ISSUE THREAD

**Issue by ISnotes** [codeaffen/phpipam-ansible-modules#118]
Hi, in the current implementation the module supports filling only standard fields in phpipam. We use [custom fileds](https://phpipam.net/news/using-custom-fields-in-phpipam/) and would like to be able to manage the values ​​in them. It would be great if this functionality appears, we will be able to use the module in our scenarios

**Comment by cmeissner** [comment]
Hi @ISnotes,

Thank you for bringing this topic to our attention. Unfortunately, this can't be implemented by us yet, as the API does not provide the possibility to manage custom fields. It also provides a limit range of operations to manage data within custom fields. [1]

You need to ask for some development on API in the phpipam project, If this is implemented once you can come back. For now, we would close this request as it can't be implemented. 

[1] - https://phpipam.net/api/api_documentation/#prefix

**Comment by urskog84** [comment]
Does anyone have any thoughts on how you want the custom failed to look like in the moldules?

``` yaml 
- name: "Create device"
  codeaffen.phpipam.device:
    username: "admin"
    password: "s3cr3t"
    server_url: "https://ipam.example.com"
    hostname: "sta-print-11"
    ipaddress: "192.1.2.22"
    custom:
        - serailnumber: "75290011489ZC"
    state: present
```

maybe I can help to wright some of the python code!
