### ISSUE TITLE
implement - location and custom_x field 

### ISSUE THREAD

**Issue by urskog84** [codeaffen/phpipam-ansible-modules#119]
almost every object in the phpIPAM database have the option to set a "location" that's correspond to the ID of the location.

would be nice to have that available int the modules.
- address
- device
- subnet

```yaml

# Example

- name: "Create device"
  codeaffen.phpipam.device:
    username: "admin"
    password: "s3cr3t"
    server_url: "https://ipam.example.com"
    hostname: "leaf-example-01"
    ipaddress: "192.0.2.222"
    location_id: 53          <--- New
    sections:
      - Example Inc.
      - DEVOPS department
    state: present
```

you can also have custom database fealds. the are all prefixed in the db with custom_xx
``` yaml 
- name: "Create device"
  codeaffen.phpipam.device:
    username: "admin"
    password: "s3cr3t"
    server_url: "https://ipam.example.com"
    hostname: "sta-print-11"
    ipaddress: "192.1.2.22"
    custom:
        - serailnumber: "75290011489ZC"

    state: present
```

when it you send to the api 

```json
{
    "id": "1660",
    "hostname": "sta-print-11",
    "ip": "192.1.2.22",
    "custom_serialnumber": "75290011489ZC",
  }
```
