### ISSUE TITLE
Creating same subnet in different sections isn't possible

### ISSUE THREAD

**Issue by cmeissner** [codeaffen/phpipam-ansible-modules#33]
**Describe the bug**

If I want to create the same subnet within different section that won't work correctly. The subnet will be created first in one group and after that the `section` parameter is changed to the next section.

```
$ ansible-playbook example_setup.yml

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [create sections] ********************************************************************************************************************************************************************************************
included: phpipam-ansible-modules/tasks/section.yml for localhost => (item={'name': 'Customer A', 'parent': 'Customers'})
included: phpipam-ansible-modules/tasks/section.yml for localhost => (item={'name': 'Customer B', 'parent': 'Customers'})

TASK [Ensure state of section: Customer A] ************************************************************************************************************************************************************************
changed: [localhost]

TASK [Ensure state of section: Customer B] ************************************************************************************************************************************************************************
changed: [localhost]

TASK [create subnet] **********************************************************************************************************************************************************************************************
included: phpipam-ansible-modules/tasks/subnet.yml for localhost => (item={'cidr': '192.0.2.0/24', 'section': 'Customer A'})
included: phpipam-ansible-modules/tasks/subnet.yml for localhost => (item={'cidr': '192.0.2.0/24', 'section': 'Customer B'})

TASK [Ensure state of subnet: 192.0.2.0/24] ***********************************************************************************************************************************************************************
changed: [localhost]

TASK [Ensure state of subnet: 192.0.2.0/24] ***********************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=8    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

![image](https://user-images.githubusercontent.com/14936920/99250631-48bd0d80-280c-11eb-9d9b-4c1926fc34e0.png)

**To Reproduce**

1. Create following configs:
**section.yml**
```
---
sections:
  - name: "Customer A"
    parent: "Customers"
  - name: "Customer B"
    parent: "Customers"
```
**subnet.yml**
```
---
subnets:
  - cidr: 192.0.2.0/24
    section: "Customer A"
  - cidr: 192.0.2.0/24
    section: "Customer B"
```

2. create task files for `section` and `subnet`
3. create following playbook:
```
---
- hosts: localhost
  collections:
    - codeaffen.phpipam
  gather_facts: false
  vars_files:
    - vars/server.yml
    - vars/section.yml
    - vars/subnet.yml
  tasks:
    - name: create sections
      include: tasks/section.yml
      vars:
        name: "{{ section.name }}"
      loop: "{{ sections }}"
      loop_control:
        loop_var: section

    - name: create subnet
      include: tasks/subnet.yml
      vars:
        name: "{{ subnet.cidr }}"
      loop: "{{ subnets }}"
      loop_control:
        loop_var: subnet
```
4. let the playbook run and see that ip subnet `192.0.2.0/24` is only assigned to `Customer B`.

**Expected behavior**

IP subnet `192.0.2.0/24` should be assigned to both sections `Customer A` and `Customer B`

**Versions:**

- Ansible: 2.9.x
- phpipam-ansible-modules: 1.2.0
- phpypam: 1.0.0

**Additional context**

If we add the IP subnet manually to both sections we get another error:

```
TASK [create subnet] **********************************************************************************************************************************************************************************************
included: phpipam-ansible-modules/tasks/subnet.yml for localhost => (item={'cidr': '192.0.2.0/24', 'section': 'Customer A'}) 
included: phpipam-ansible-modules/tasks/subnet.yml for localhost => (item={'cidr': '192.0.2.0/24', 'section': 'Customer B'}) 

TASK [Ensure state of subnet: 192.0.2.0/24] ***********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Found too many (2) results while searching for subnets at cidr/192.0.2.0/24"}
```

This is possibly because we don't accept result set greater than one.
