### ISSUE TITLE
Trouble creating subnet with a vrf

### ISSUE THREAD

**Issue by ishuguru** [codeaffen/phpipam-ansible-modules#93]
**Describe the bug**
Cant assign a subnet with a custom vrf

**To Reproduce**

```
  - name: "Create subnet"
    codeaffen.phpipam.subnet:
       app_id: "ansible"
       username: "ansible"
       password: "{{password}}"
       server_url: "https://ipam.internal"
       cidr: "192.168.1.0/27"
       parent: "192.168.1.0/24"
       vlan: "1337"
       vrf: FW-Linknets
       location: "DC1"
       validate_certs: no
       section: "Linknets"
       routing_domain: DC1

```
**Expected behavior**
Have the subnet created in the correct subnets

**Versions:**

- Ansible: core 2.12.3
- phpipam-ansible-modules: 1.6.0
- phpypam: Version: 1.0.2

**Additional context**
I see this error:
 ```
       }
    },
    "msg": "Can not resolve 'vrf' to an existing ID"
}
```
